services:
  web:
    build: .
    container_name: image_optimizer_app
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    env_file:
      - .env
    command: >
      bash -c "python manage.py migrate --noinput &&
              python manage.py collectstatic --noinput &&
              gunicorn --workers=1 --bind 0.0.0.0:8001 second_app.wsgi:application"


  nginx:
      image: nginx:1.23-alpine
      container_name: image_optimizer_nginx
      restart: unless-stopped
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./nginx/auth:/etc/nginx/auth
        - ./nginx/ssl:/etc/nginx/ssl
        - ./static:/app/static
      depends_on:
        - web